### ISSUE TITLE
editor not working on ipad mini 1, version  9.3.5

### ISSUE THREAD

**Issue by wingbui** [jsitor/jsitor#25]
The editor is just blank on ios v.9.3.5 on my Ipad Mini 1, so I cannot type in the codes.

Edit: I just install jsitor today, sure it is the lastest version. On my iphone SE iso v.12 it works fine. On my ipad gen 1, iso v.9.3.5 it has the blank issue as described above

**Comment by wingbui** [comment]
just attach a photo to show that.

**Comment by ashvin777** [comment]
Hi Wingbui,

Thanks for reporting the issue. We will try to reproduce the problem. We are extremely sorry for this behaviour.

Please share the screenshot of what you are seeing if possible so that we will get better idea about the problem. Make sure you have the latest version of JSitor installed. If you are already having that then its great.

Thanks for using JSitor.

**Comment by wingbui** [comment]
![AFF4A381-AC8A-4CBF-80ED-ADA16DD363CF](https://user-images.githubusercontent.com/38932460/60396764-a2695d00-9b6f-11e9-9eec-c4130edb723a.png)

**Comment by ashvin777** [comment]
Thanks @wingbui. I am checking the issue and will get back to you soon.

**Comment by ashvin777** [comment]
Hi @wingbui , We have fixed some major issues in our latest build. Request you to verify the same issues in the latest build.
