### ISSUE TITLE
Snippets not being synced.

### ISSUE THREAD

**Issue by pinglu85** [jsitor/jsitor#57]
Snippets are not being synced between web app and iOS app.

**Comment by ashvin777** [comment]
Hi @pinglu85 , Yes that is true due to some major upgrades we have done on our platform. You will still be able to access your mobile snippets on v1.jsitor.com, however you won't be able to access snippets that are created on jsitor.com. 

We will soon release and update which will fix this problem.

**Comment by CastroSATT** [comment]
please its killing me i love the app hhehe

**Comment by ashvin777** [comment]
Request you to wait for couple more days. Its coming for sure very soon, I am trying my best to get it out as soon as possible.

Sharing some glimpse
![image](https://user-images.githubusercontent.com/8143154/110199635-4e079c00-7e7f-11eb-9b8f-a9da1f15a98e.png)

**Comment by ashvin777** [comment]
Its not just a fix but a brand new design. 🙂

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store.

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773

**Comment by pinglu85** [comment]
Thank you very much.
