### ISSUE TITLE
Deleted snippets will reappear after a while

### ISSUE THREAD

**Issue by typable** [jsitor/jsitor#69]
The delete process behaves as expected and after reloading the page the snippet is gone.
But after a day or two, the deleted snippet reappears in my snippets view.

OS: Windows, Linux
Browser: Chrome (Latest Version)

**Comment by ashvin777** [comment]
Hey @typable , Yes we are aware of this and this is happening for snippets created using mobile app.

This is all happening because of some migration tasks, as mobile and desktop version are now running on different instances. 

We are soon going to fix this because we are working on the newer version of mobile app which will eventually fix this problem.

Stay tuned, soon this will be resolved.

A snapshot of newer app coming soon 🙂

![image](https://user-images.githubusercontent.com/8143154/102849825-fb047800-443d-11eb-9c66-bbd8454f712a.png)

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store. 

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
