### ISSUE TITLE
Javascript tab from phone app not seen on web app version

### ISSUE THREAD

**Issue by glencouls** [jsitor/jsitor#72]
Javascript is saved as a snippet on my phone along with HTML and CSS. When i go open my snippet on the jsitor webapp (site) all of the javascript I wrote is missing. The site still has the original HTML and CSS i wrote on phone, but the javascript i created (65 lines of code) are just blank. It's like the javascript tab is a new tab. The breaks my code snippet, as the javascript really did all the heavy lifting. 

**To Reproduce**
1. Go to phone and type a bunch of awesome useful code in the javascript tab
2. Next, login to jsitor website. Access your snippet, the code is not there.
3. Try it both chrome and Firefox, be bummed you can't get your code.
4. Complain to management.

**Expected behavior**
A clear and concise description of what you expected to happen. I expected to have the same snippet on both webapp and the jsitor application on my phone.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome, edge
 - Version modern I don't know version off the top of my head

**Smartphone (please complete the following information):**
 - Device: Samsung note 10+
 - OS: Android v10
 - Browser chrome and firefox
 - Version [e.g. 22] chrome 87, Firefox 84.1.2

**Additional context**

**Comment by ashvin777** [comment]
Thanks @glencouls , Yes there is a issue related to this. However after sometime it shows up in the website. As it runs through our backend migration at a particular interval.

This is happening because of app and site are running on different version. The app is in development to upgrade to newer version and ux which will eventually fix this issue.

Please recheck and confirm if your snippets are showing up or not.

With our new apps coming soon we will solve this issue all together.

Some screenshot of new app
![image](https://user-images.githubusercontent.com/8143154/103432359-a31afd80-4c03-11eb-8b1c-30e5c394c913.png)
![image](https://user-images.githubusercontent.com/8143154/103432366-a9a97500-4c03-11eb-974a-1dbedddd9a56.png)

**Comment by ashvin777** [comment]
🎉🎉 This is now available in both Android and Apple store. 

**Play Store**
https://play.google.com/store/apps/details?id=com.ashvin777.apps.jsitor&hl=en_US

**App Store**
https://apps.apple.com/us/app/jsitor-advance-web-editor/id1455784773
